---
abstract: 'Handles arrays of scalars or objects using integer ranges'
author:
  - 'Dominique Dumont'
build_requires:
  Data::Dumper: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Array-IntSpan
provides:
  Array::IntSpan:
    file: lib/Array/IntSpan.pm
    version: '2.004'
  Array::IntSpan::Fields:
    file: lib/Array/IntSpan/Fields.pm
    version: '2.004'
  Array::IntSpan::IP:
    file: lib/Array/IntSpan/IP.pm
    version: '2.004'
requires:
  Carp: '0'
  perl: '5.008'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Array-IntSpan
  homepage: https://github.com/dod38fr/array-intspan-perl
  repository: https://github.com/dod38fr/array-intspan-perl.git
version: '2.004'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Artistic-2.0
